CREATE DATABASE template DEFAULT CHARACTER SET UTF8;

CREATE DATABASE workflow DEFAULT CHARACTER SET UTF8;

CREATE USER 'b112'@'template' IDENTIFIED BY '112';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, LOCK TABLES, EXECUTE ON *.* TO 'b112'@'template';

CREATE USER 'b112'@'workflow' IDENTIFIED BY '112';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, LOCK TABLES, EXECUTE ON *.* TO 'b112'@'workflow';